# Generated by Django 3.2.8 on 2021-10-20 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20211019_1736'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='status_of_article',
            new_name='status',
        ),
    ]
