# Generated by Django 3.2.8 on 2021-10-20 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_rename_status_of_article_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='articles/'),
        ),
    ]
