# Generated by Django 3.2.8 on 2021-10-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('NEWS', 'News'), ('HLTH', 'Health'), ('SPRT', 'Sports'), ('TECH', 'Tech'), ('OPIN', 'Opinion')], default='NEWS', max_length=4),
        ),
    ]
